import type { AuditRow } from "./NightAuditDataType";

export const initialData: AuditRow[] = [
  {
    id: 1,
    roomNo: 101,
    guestName: "John Doe",
    service: "Room Cleaning",
    roomTariff: 200,
    sCharge: 20,
    vatAmount: 15,
    total: 235,
    remarks: "VIP Guest",
    audit: "Room Audit",
  },
  {
    id: 2,
    roomNo: 102,
    guestName: "Alice Smith",
    service: "Laundry",
    roomTariff: 180,
    sCharge: 18,
    vatAmount: 14,
    total: 212,
    remarks: "Urgent Delivery",
    audit: "Service Audit",
  },
  {
    id: 3,
    roomNo: 103,
    guestName: "Robert Lee",
    service: "Dinner",
    roomTariff: 300,
    sCharge: 30,
    vatAmount: 20,
    total: 350,
    remarks: "Regular Customer",
    audit: "Restaurant Audit",
  },
  {
    id: 4,
    roomNo: 104,
    guestName: "Jane Foster",
    service: "Banquet Service",
    roomTariff: 500,
    sCharge: 50,
    vatAmount: 40,
    total: 590,
    remarks: "Corporate Event",
    audit: "Banquet Audit",
  },
  {
    id: 5,
    roomNo: 105,
    guestName: "Tom Hanks",
    service: "Room Cleaning",
    roomTariff: 220,
    sCharge: 22,
    vatAmount: 16,
    total: 258,
    remarks: "VIP Guest",
    audit: "Room Audit",
  },
  {
    id: 6,
    roomNo: 106,
    guestName: "Emma Watson",
    service: "Laundry",
    roomTariff: 190,
    sCharge: 19,
    vatAmount: 15,
    total: 224,
    remarks: "Express Service",
    audit: "Service Audit",
  },
  {
    id: 7,
    roomNo: 107,
    guestName: "Chris Evans",
    service: "Breakfast",
    roomTariff: 150,
    sCharge: 15,
    vatAmount: 10,
    total: 175,
    remarks: "Regular Customer",
    audit: "Restaurant Audit",
  },
  {
    id: 8,
    roomNo: 108,
    guestName: "Scarlett Johansson",
    service: "Banquet Setup",
    roomTariff: 480,
    sCharge: 48,
    vatAmount: 38,
    total: 566,
    remarks: "Corporate Event",
    audit: "Banquet Audit",
  },
  {
    id: 9,
    roomNo: 109,
    guestName: "Robert Downey Jr.",
    service: "Room Cleaning",
    roomTariff: 210,
    sCharge: 21,
    vatAmount: 16,
    total: 247,
    remarks: "VIP Guest",
    audit: "Room Audit",
  },
  {
    id: 10,
    roomNo: 110,
    guestName: "Natalie Portman",
    service: "Laundry",
    roomTariff: 185,
    sCharge: 18,
    vatAmount: 14,
    total: 217,
    remarks: "Urgent Delivery",
    audit: "Service Audit",
  },
  {
    id: 11,
    roomNo: 111,
    guestName: "Leonardo DiCaprio",
    service: "Lunch",
    roomTariff: 320,
    sCharge: 32,
    vatAmount: 22,
    total: 374,
    remarks: "Regular Customer",
    audit: "Restaurant Audit",
  },
  {
    id: 12,
    roomNo: 112,
    guestName: "Anne Hathaway",
    service: "Banquet Cleanup",
    roomTariff: 510,
    sCharge: 51,
    vatAmount: 41,
    total: 602,
    remarks: "Corporate Event",
    audit: "Banquet Audit",
  },
];
